# Generated by Django 3.2.4 on 2021-07-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashsell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellbool', models.BooleanField(default=False)),
                ('start_price', models.IntegerField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
    ]
